FROM python:3.8

WORKDIR /home

ENV TELEGRAM_API_TOKEN=""
ENV TELEGRAM_ACCESS_ID=""
ENV TELEGRAM_PROXY_URL=""
ENV TELEGRAM_PROXY_LOGIN=""
ENV TELEGRAM_PROXY_PASSWORD=""

RUN pip install -U pip aiogram pytz gspread oauth2client
RUN apt-get update && apt-get install sqlite3

COPY env/gsheet_token_dev.json ./env/
COPY *.py ./
COPY createdb.sql ./

ENTRYPOINT ["python", "server.py"]

